export const TOGGLE_BASIC_CATEGORY = 'LOCATIONS / TOGGLE_BASIC_CATEGORY';
export const TOGGLE_CUSTOM_CATEGORY = 'LOCATIONS / TOGGLE_CUSTOM_CATEGORY';
export const TOGGLE_BASIC_LOCATION = 'LOCATIONS / TOGGLE_BASIC_LOCATION';
export const UPDATE_CUSTOM = 'LOCATIONS / UPDATE_CUSTOM';
export const SET_LOCATION_FOR_GAME = 'LOCATIONS / SET_LOCATION_FOR_GAME';
