export const TOGGLE_BASIC = 'LOCATIONS / TOGGLE_BASIC';
export const TOGGLE_CUSTOM = 'LOCATIONS / TOGGLE_CUSTOM';
export const UPDATE_BASIC = 'LOCATIONS / UPDATE_BASIC';
export const UPDATE_CUSTOM = 'LOCATIONS / UPDATE_CUSTOM';
export const SET_LOCATION_FOR_GAME = 'LOCATIONS / SET_LOCATION_FOR_GAME';
