export enum SCREENS {
    START_SCREEN = 'START_SCREEN',
    RULES = 'RULES',
    SETTINGS = 'SETTINGS',
    PLAYER_PROFILE = 'PLAYER_PROFILE',
    BASIC_LOCATIONS = 'BASIC_LOCATIONS',
    CUSTOM_LOCATIONS = 'CUSTOM_LOCATIONS',
    ROLES_DISTRIBUTION = 'ROLES_DISTRIBUTION',
    QUESTIONS = 'QUESTIONS',
    DISCUSSION = 'DISCUSSION',
    IDENTIFY_SPIES = 'IDENTIFY_SPIES',
    RESULTS = 'RESULTS',
}

export enum SETTINGS_SCREENS {
    PLAYERS = 'PLAYERS',
    SPIES = 'SPIES',
    TIME = 'TIME',
    LOCATIONS = 'LOCATIONS',
}

export const SET_SCREEN = 'SCREEN / SET_SCREEN';
export const SET_SETTINGS_SCREEN = 'SCREEN / SET_SETTINGS_SCREEN';
export const SET_PLAYER_PROFILE_SCREEN = 'SCREEN / SET_PLAYER_PROFILE_SCREEN';
export const SET_BASIC_LOCATIONS_SCREEN = 'SCREEN / SET_BASIC_LOCATIONS_SCREEN';
export const SET_CUSTOM_LOCATIONS_SCREEN = 'SCREEN / SET_CUSTOM_LOCATIONS_SCREEN';
export const SET_PREVIOUS_SCREEN = 'SCREEN / SET_PREVIOUS_SCREEN';
