export const SET_QUESTIONS_TIME_LIMIT = 'TIME / SET_QUESTIONS_TIME_LIMIT';
export const SET_QUESTIONS_TIME_START = 'TIME / SET_QUESTIONS_TIME_START';
export const SET_DISCUSSION_TIME_LIMIT = 'TIME / SET_DISCUSSION_TIME_LIMIT';
export const SET_DISCUSSION_TIME_START = 'TIME / SET_DISCUSSION_TIME_START';
export const TOGGLE_SOUND = 'TIME / TOGGLE_SOUND';
