name: Spyfall CI with CD to Github Pages
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install, Lint and Build
      run: |
        yarn install --frozen-lockfile
        yarn run lint
        yarn run build
        yarn run export
      env:
        ASSET_PREFIX: /spyfall
        NEXT_TELEMETRY_DISABLED: 1

    - name: Deploy
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_SPYFALL }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: out # The folder the action should deploy.
      env:
        HUSKY_SKIP_HOOKS: 1
   
